# Generated by Django 3.1.6 on 2021-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0005_auto_20210214_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('hy', 'Armenian'), ('az', 'Azerbaijani'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('ceb', 'Cebuano'), ('zh-TW', 'Chinese (Traditional)'), ('zh', 'Chinese (Simplified)'), ('co', 'Corsican'), ('sv', 'Swedish'), ('it', 'Italian')], max_length=6),
        ),
    ]
