# Generated by Django 3.1.6 on 2021-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_auto_20210219_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('hy', 'Armenian'), ('az', 'Azerbaijani'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('ceb', 'Cebuano'), ('zh-TW', 'Chinese (Traditional)'), ('zh', 'Chinese (Simplified)'), ('co', 'Corsican'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('de', 'German'), ('he', 'Hebrew'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('la', 'Latin'), ('ms', 'Malay'), ('ny', 'Nynja'), ('fa', 'Persian'), ('ro', 'Romanian'), ('es', 'Spanish'), ('th', 'Thai'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('cy', 'Welsh'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('zu', 'Zulu')], max_length=20),
        ),
    ]
